[build-system]
requires = ['setuptools>=42', 'pvlib>=0.9.1', 'retry_requests>=2.0.0', 'openmeteo_requests>=1.1.0', 'requests_cache>=1.1.0', 'pandas>=1.5.2', 'numpy>=1.22.4', 'tzfpy>=0.15.1', 'meteostat>=1.6.5', 'scipy>=1.10.0']
build-backend = 'setuptools.build_meta'